name: Bet365 Scraper

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu yüklə
        uses: actions/checkout@v3

      - name: Python quraşdır
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Tələbləri quraşdır
        run: pip install -r requirements.txt

      - name: Playwright-i quraşdır
        run: playwright install chromium

      - name: Scraper-i işə sal
        run: python main.py
