name: Run Bet365 Scraper

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Kod yükla
      uses: actions/checkout@v2

    - name: Python quraşdır
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Tələbləri quraşdır
      run: pip install requests

    - name: Scraper-i işə sal
      run: python main.py

    - name: Upload HTML file
      uses: actions/upload-artifact@v3
      with:
        name: bet365-html
        path: page.html
