name: Run Scraper

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu yüklə
        uses: actions/checkout@v3

      - name: Python quraşdır
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: PIP yenilə
        run: python -m pip install --upgrade pip

      - name: Asılılıqları quraşdır
        run: pip install -r requirements.txt

      - name: Playwright komponentlərini quraşdır
        run: playwright install --with-deps

      - name: Scraper-i işə sal
        run: python main.py
